/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sci.mfem;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import sci.mfem.LaghosMeshReader;

class LaghosMeshReaderTest {
    String meshDir = "/home/bsettlemyer/workspace/glass-ceiling/data";

    @Test void TestSomething() {
        String meshFile = meshDir + "/snoise_60_mesh";
        String eFile = meshDir + "/snoise_60_e";
        String rhoFile = meshDir + "/snoise_60_rho";
        String vFile = meshDir + "/snoise_60_v";
        //LaghosMeshReader lmr = new LaghosMeshReader(meshFile, eFile, rhoFile, vFile);
        //lmr.close();
        assertEquals(0, 0);
    }
}
